version: "3.10"

services:
  db:
    container_name: "zno"
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: python-app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python app.py
    volumes:
      - ./app/:/app/
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres:
    external: true
  pgadmin:
    external: true
